apiVersion: v1
kind: Template
labels:
  template: springboot-pipeline-dev
metadata:
  annotations:
    description: Pipeline Dev SpringBoot S2I
    iconClass: icon-jenkins
    tags: java,springboot,jenkins,dev
  creationTimestamp: null
  name: springboot-pipeline-dev
objects:
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      name: ${APP_NAME}-pipeline-dev
    spec:
      source:
        git:
          uri: ${GIT_REPO_PIPELINE}
        type: Git
      strategy:
        jenkinsPipelineStrategy:
          jenkinsfilePath: Jenkinsfile-dev
          env:
          - name: PROJECT_NAME
            value: ${BASE_PROJECT_NAME}-dev
          - name: APP_NAME
            value: ${APP_NAME}
          - name: GIT
            value: ${GIT_REPO_URL}
      output: 
        to:
          kind: ImageStreamTag
          name: ${APP_NAME}:latest
parameters:
- description: Git Project Repository.
  displayName: Git Project Repository
  name: GIT_REPO_URL
  required: true
- description: The base project name
  displayName: Base project name
  name: BASE_PROJECT_NAME
  required: true
- description: The name assigned to the application.
  displayName: Application Name
  name: APP_NAME
  required: true
- description: Git pipeline repository.
  displayName: Git pipeline repository.
  name: GIT_REPO_PIPELINE
  required: true
