apiVersion: v1
kind: Template
labels:
  template: springboot-deployconfig
metadata:
  annotations:
    description: SpringBoot S2I
    iconClass: icon-spring
    tags: java,springboot
  creationTimestamp: null
  name: springboot-deployconfig
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    replicas: 1
    selector:
      app: ${APP_NAME}
      deploymentconfig: ${APP_NAME}
    strategy:
      resources: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: ${APP_NAME}
          deploymentconfig: ${APP_NAME}
      spec:
        serviceAccountName: ${SERVICE_ACCOUNT}
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: library/${APP_NAME}:latest
          name: ${APP_NAME}
          ports:
          - containerPort: 8080
            name: http
          - containerPort: 8778
            name: jolokia
          - containerPort: 8081
            name: management
          resources:
            limits:
              cpu: ${CPU_LIMIT}
            requests:
              cpu: ${CPU_REQUEST}
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${APP_NAME}
        from:
          kind: ImageStreamTag
          name: ${APP_NAME}:${TAG_NAME}
          namespace: ${NAMESPACE}
      type: ImageChange
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: ${APP_NAME}
      template: springboot
    name: ${APP_NAME}
  spec:
    ports:
    - name: port-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: port-8778
      port: 8778
      protocol: TCP
      targetPort: 8778
    - name: port-8443
      port: 8443
      protocol: TCP
      targetPort: 8443
    selector:
      app: ${APP_NAME}
      deploymentconfig: ${APP_NAME}
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Route
  metadata:
    creationTimestamp: null
    labels:
      app: ${APP_NAME}
      template: springboot
    name: ${APP_NAME}
  spec:
    port:
      targetPort: port-8080
    to:
      kind: Service
      name: ${APP_NAME}
      weight: 100
    wildcardPolicy: None
  status:
    ingress:
    - conditions:
      - lastTransitionTime: null
        status: "True"
        type: Admitted
      routerName: router
      wildcardPolicy: None
parameters:
- description: The name assigned to the application.
  displayName: Application Name
  name: APP_NAME
  required: true
- description: Namespace in which the ImageStream is installed.
  displayName: Image Stream Namespace
  name: NAMESPACE
  required: true
  value: openshift
- description: The amount of CPU to requests.
  displayName: CPU request
  name: CPU_REQUEST
  required: true
  value: "0.2"
- description: The amount of CPU the container is limited to use.
  displayName: CPU limit
  name: CPU_LIMIT
  required: true
  value: "1.0"
- description: Service Account
  displayName: Service Account
  name: SERVICE_ACCOUNT
  required: true
- description: Tag name
  displayName: Tag name
  name: TAG_NAME
  required: true
  value: latest